apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-kub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
#    matchExpressions:
#      - key: app
#        operator: In
#        values:
#          - second-app
#          - first-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-node
          image: mriabov/kubernetes-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            periodSeconds: 10
            initialDelaySeconds: 20

